import {missions,gamer,phrases,songs,songDistractors,recipes,diloWords,drawRounds,drawingWords,people} from '../data/game-data.js';
const app=document.querySelector('#app'); const KEY='mbq-final-progress';
const getState=()=>JSON.parse(localStorage.getItem(KEY)||'{"done":{},"coins":30}');
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
const shuffle=a=>[...a].sort(()=>Math.random()-.5); const esc=s=>String(s).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
const missionId=()=>new URLSearchParams(location.search).get('mission');
function complete(id,title,detail,coins=100){const s=getState();if(!s.done[id]){s.done[id]=true;s.coins+=coins;save(s)}confetti();app.innerHTML=hud()+`<section class="card"><div class="intro-icon">🏆</div><h1>${title}</h1><p class="rank">${detail}</p><p>⭐ +1 estrella &nbsp; 🪙 +${coins} monedas</p><button class="btn" onclick="location.href='./'">Volver al mapa</button></section>`}
function hud(){const s=getState(),done=Object.keys(s.done).length;return `<div class="hud"><span class="lives">❤️❤️❤️</span><span>🪙 ${s.coins}</span><span>⭐ ${done}/${missions.length-1}</span><span class="grow"></span><button onclick="location.href='./'">🗺️</button></div>`}
function intro(m,text){return `<section class="card"><div class="intro-icon">${m.icon}</div><h1>${m.title}</h1><p>${text}</p></section>`}
function home(){const s=getState();return `<section class="hero"><div class="logo">Marina's<br>Birthday Quest</div><div class="subtitle">La aventura para alcanzar el nivel 30 🍄</div></section><section class="card"><h2>🗺️ Mapa de misiones</h2><div class="mission-grid">${missions.map(m=>`<button class="mission ${s.done[m.id]?'done':''}" onclick="location.href='?mission=${m.id}'"><div class="ico">${m.icon}</div><h3>${m.title}</h3><p>${s.done[m.id]?'✅ completada':'▶ disponible'}</p></button>`).join('')}</div></section><div class="footer"><button class="btn secondary" id="reset">Reiniciar progreso</button></div>`}
function render(){const id=missionId();app.innerHTML=hud()+(id?mission(id):home());bind(id)}
function mission(id){const m=missions.find(x=>x.id===id);if(!m)return `<section class="card"><h2>Misión no encontrada</h2><button class="btn" onclick="location.href='./'">Volver</button></section>`;
if(id==='gamer'||id==='frases')return quizView(m,id==='gamer'?gamer:phrases,id);
if(id==='perros')return intro(m,'Tienes 30 segundos para decir 15 razas de perros diferentes.')+timerView('dog',30,'No se pueden repetir razas y no vale “mestizo”.');
if(id==='musica')return intro(m,'Escucha solo 5 segundos. Los fragmentos evitan el título y las opciones cambian en cada canción.')+`<section class="card" id="music"><div class="progress"><div class="bar"></div></div><div class="record"></div><h2 id="trackLabel">Pista 1/${songs.length}</h2><button class="btn" id="play">▶ Escuchar 5 segundos</button><div class="options" id="musicOptions"></div><audio id="audio"></audio></section>`;
if(id==='cocina')return intro(m,'Selecciona exactamente los ingredientes correctos de 10 recetas. Hay trampas bastante creíbles.')+`<section class="card" id="recipe"><div class="progress"><div class="bar"></div></div><h2 id="recipeName"></h2><p id="recipeCount"></p><div class="recipe-grid" id="ingredients"></div><button class="btn" id="checkRecipe">Comprobar receta</button><p id="recipeFeedback"></p></section>`;
if(id==='dilo')return intro(m,'Haz que el grupo adivine 5 palabras sin decirlas, sin derivados y sin señalar.')+`<section class="card" id="dilo"><h2>Palabra <span id="wordNum">1</span>/5</h2><div class="big-word" id="word"></div><button class="btn ok" id="got">✔ Adivinada</button><button class="btn secondary" id="pass">⏭ Pasar</button></section>`;
if(id==='letras')return intro(m,'Dos jugadores se enfrentan. A la de tres, cada uno dice una letra.')+`<section class="card"><h2>⚔️ Reglas</h2><p>El jugador de la izquierda aporta la letra inicial y el de la derecha la letra final.</p><p>Los dos deben pensar una palabra que empiece por la primera y termine por la segunda. Ejemplo: <b>S + A → SUELA</b>.</p><p>El primero que diga una palabra válida gana. El vencedor reta a otra persona hasta derrotar a todos.</p><button class="btn ok" id="doneSimple">Arena conquistada</button></section>`;
if(id==='dibujo')return intro(m,'Tres rondas. 30 segundos para dibujar sin levantar el lápiz del papel.')+`<section class="card" id="drawing"><h2>Ronda <span id="roundNum">1</span>/3</h2><div class="big-word" id="drawPrompt"></div><div class="timer" id="drawTimer">30</div><button class="btn" id="startDraw">▶ Empezar 30 s</button><button class="btn secondary" id="nextDraw">Siguiente ronda</button><p>Al final, Marina vota el mejor, el peor y el más WTF.</p></section>`;
if(id==='inutil')return intro(m,'Marina tiene exactamente un minuto para mostrar un talento completamente inútil.')+timerView('useless',60,'Puede hacer una voz rara, contar un chiste malo, doblar los dedos de forma extraña… cuanto más absurdo, mejor. El grupo vota al Gran Maestro de lo Inútil.');
if(id==='frases')return '';
if(id==='quien')return intro(m,'Adivina quién es cada persona transformada. Si aparece un hombre, solo salen nombres de mujeres; y viceversa.')+`<section class="card" id="who"><div class="progress"><div class="bar"></div></div><h2 id="whoCount"></h2><div id="whoMedia"></div><div class="options" id="whoOptions"></div></section>`;
if(id==='bingo')return intro(m,'Cada invitado utiliza su cartón impreso. La web solo dirige la misión.')+`<section class="card"><h2>🎼 Cómo se juega</h2><p>Reparte los cartones. Haz sonar las canciones de vuestra lista. Cada persona marca la canción si aparece en su cartón.</p><p>Podéis premiar primero la <b>línea</b> y después el <b>bingo completo</b>.</p><div class="big-word">Cuando alguien complete el cartón debe gritar: ¡BINGO MUSICAL!</div><button class="btn ok" id="doneSimple">Bingo terminado</button></section>`;
if(id==='video')return intro(m,'Un pequeño viaje por vuestros recuerdos.')+`<section class="card video-link-card"><div class="intro-icon">🎬❤️</div><h2>El viaje de los recuerdos</h2><p>Dicen que los mejores momentos pasan demasiado rápido… Por suerte, algunos quedan para siempre.</p><a class="btn" href="https://drive.google.com/file/d/1uzaJas8O4pBXM7B4U0Gwo5StfAx85Lsc/view?usp=sharing" target="_blank" rel="noopener noreferrer">▶ Ver vídeo</a><button class="btn ok" id="doneSimple">He terminado ❤️</button></section>`;
if(id==='dibuja')return intro(m,'Primero dibuja rápidamente las 20 palabras en las casillas numeradas del folio. Después intenta recordar qué representaba cada número.')+`<section class="card"><h2>✏️ Lista del 1 al 20</h2><ol class="list20">${drawingWords.map(w=>`<li>${w}</li>`).join('')}</ol><div class="notice">Haz los dibujos rápido y sin escribir palabras. Cuando termines, tapa la lista.</div><button class="btn" id="randomNumber">Sacar número al azar</button><div class="big-word" id="randomResult">—</div><button class="btn ok" id="doneSimple">Misión completada</button></section>`;
if(id==='acertijos')return intro(m,'Resuelve los dos acertijos antes de descubrir la solución.')+`<section class="card"><div class="riddle"><h2>🦁 Acertijo 1</h2><p>Un prisionero tiene que elegir una de estas tres habitaciones para escapar:</p><p>La primera está llena de fuego.<br>La segunda tiene asesinos con armas cargadas.<br>La tercera está llena de leones que llevan tres años sin comer.</p><p><b>¿Cuál debe elegir?</b></p><button class="btn secondary reveal">Ya tenemos respuesta</button><div class="solution">La tercera. Los leones llevarían muertos mucho antes de tres años sin comer.</div></div><div class="riddle"><h2>🌉 Acertijo 2</h2><p>Dos padres y dos hijos cruzan un puente. Solo hay tres personas.</p><p><b>¿Cómo puede ser?</b></p><button class="btn secondary reveal">Ya tenemos respuesta</button><div class="solution">Son un abuelo, su hijo y su nieto.</div></div><button class="btn ok" id="doneSimple">Acertijos resueltos</button></section>`;
if(id==='final'){const s=getState(),done=Object.keys(s.done).filter(x=>x!=='final').length;return `<section class="hero"><div class="logo">Nivel 30<br>Completado</div></section><section class="card final-message"><div class="intro-icon">🎉🏆🎉</div><p class="rank">${done}/${missions.length-1} misiones completadas</p><p>Has superado todos los retos, has demostrado que eres una auténtica gamer, una chef de primera y una experta en reconocer a tus amigos.</p><p>Pero este juego nunca ha ido realmente de ganar.</p><p>Ha ido de recordar todos esos momentos que hemos vivido contigo.</p><p>De todas las risas.</p><p>De todos los viajes.</p><p>De todas las cenas.</p><p>De todas las fotos.</p><p>De todas las frases que solo nosotros entendemos.</p><p>Y de todos esos recuerdos que hacen que hoy estemos aquí celebrando contigo un día tan especial.</p><p class="heart-line">❤️</p><p>Gracias por estar siempre ahí.</p><p>Gracias por todos los momentos que hemos compartido.</p><p>Y, sobre todo, gracias por todos los que aún nos quedan por vivir.</p><p>Porque, al final, los mejores recuerdos nunca son los que ya tenemos... sino todos los que todavía están por venir.</p><h2>¡TE QUEREMOS!</h2><h1>¡Felices 30, Marina!</h1><button class="btn ok" id="finishGame">Cerrar la aventura</button></section>`}
return intro(m,'Próximamente');}
function timerView(kind,seconds,text){return `<section class="card"><p>${text}</p><div class="timer" id="timer">${seconds}</div><button class="btn" id="startTimer">▶ Empezar</button><button class="btn ok" id="finishTimer">Misión superada</button></section>`}
function quizView(m,data,id){return intro(m,id==='gamer'?'Preguntas de Mario, Luigi’s Mansion, Stardew Valley, Mario Odyssey y Among Us.':'Identifica quién dijo cada frase o protagonizó cada conversación.')+`<section class="card" id="quiz"><div class="progress"><div class="bar"></div></div><div class="question" id="question"></div><div class="options" id="options"></div></section>`}
function bind(id){document.querySelector('#reset')?.addEventListener('click',()=>{if(confirm('¿Reiniciar todo el progreso?')){localStorage.removeItem(KEY);render()}});if(id==='gamer')bindQuiz(gamer,'gamer');if(id==='frases')bindQuiz(phrases,'frases');if(id==='perros')bindTimer('perros',30);if(id==='inutil')bindTimer('inutil',60);if(id==='musica')bindMusic();if(id==='cocina')bindRecipes();if(id==='dilo')bindDilo();if(id==='dibujo')bindDrawing();if(id==='quien')bindWho();if(['letras','bingo','video','dibuja','acertijos'].includes(id))document.querySelector('#doneSimple')?.addEventListener('click',()=>complete(id,'¡Misión completada!',missions.find(m=>m.id===id).title));if(id==='dibuja')bindRandom();if(id==='acertijos')document.querySelectorAll('.reveal').forEach(b=>b.onclick=()=>b.nextElementSibling.style.display='block');if(id==='final')document.querySelector('#finishGame')?.addEventListener('click',()=>complete('final','¡Aventura completada!','Feliz nivel 30',300));}
function bindQuiz(data,id){let i=0,score=0;const draw=()=>{if(i>=data.questions.length){return complete(id,score>=data.pass?'¡Misión superada!':'¡Fin del reto!',`${score}/${data.questions.length} aciertos`)}const q=data.questions[i];document.querySelector('.bar').style.width=`${(i/data.questions.length)*100}%`;document.querySelector('#question').innerHTML=`<small>Pregunta ${i+1}/${data.questions.length}</small><br>${esc(q.q).replaceAll('\n','<br>')}`;const opts=document.querySelector('#options');opts.innerHTML=shuffle(q.o).map(o=>`<button class="option">${esc(o)}</button>`).join('');opts.querySelectorAll('button').forEach(b=>b.onclick=()=>{opts.querySelectorAll('button').forEach(x=>x.disabled=true);const ok=b.textContent===q.a;b.classList.add(ok?'correct':'wrong');if(ok)score++;setTimeout(()=>{i++;draw()},650)})};draw()}
function bindTimer(id,seconds){let int;document.querySelector('#startTimer').onclick=()=>{clearInterval(int);let n=seconds;document.querySelector('#timer').textContent=n;int=setInterval(()=>{n--;document.querySelector('#timer').textContent=n;if(n<=0){clearInterval(int);document.querySelector('#timer').textContent='¡TIEMPO!'}},1000)};document.querySelector('#finishTimer').onclick=()=>complete(id,'¡Misión superada!',missions.find(m=>m.id===id).title)}
function bindMusic(){let i=0,score=0,stop;const audio=document.querySelector('#audio'),play=document.querySelector('#play'),opts=document.querySelector('#musicOptions');const draw=()=>{if(i>=songs.length)return complete('musica','Radio Retro superada',`${score}/${songs.length} canciones`);const s=songs[i];document.querySelector('.bar').style.width=`${(i/songs.length)*100}%`;document.querySelector('#trackLabel').textContent=`Pista ${i+1}/${songs.length}`;opts.innerHTML='';play.disabled=false;play.onclick=()=>{clearTimeout(stop);audio.src=s.file;audio.currentTime=s.start;audio.play().catch(()=>{});document.querySelector('.record').classList.add('playing');play.disabled=true;stop=setTimeout(()=>{audio.pause();document.querySelector('.record').classList.remove('playing');show(s)},5000)}};const show=s=>{const wrong=shuffle(songDistractors.filter(x=>x!==s.title)).slice(0,3);opts.innerHTML=shuffle([s.title,...wrong]).map(x=>`<button class="option">${x}</button>`).join('');opts.querySelectorAll('button').forEach(b=>b.onclick=()=>{opts.querySelectorAll('button').forEach(x=>x.disabled=true);const ok=b.textContent===s.title;b.classList.add(ok?'correct':'wrong');if(ok)score++;setTimeout(()=>{i++;draw()},700)})};draw()}
function bindRecipes(){let i=0,score=0,selected=new Set();const draw=()=>{if(i>=recipes.length)return complete('cocina','MasterChef completado',`${score}/${recipes.length} recetas perfectas`,150);const r=recipes[i];selected=new Set();document.querySelector('.bar').style.width=`${(i/recipes.length)*100}%`;document.querySelector('#recipeName').textContent=`${i+1}. ${r.name}`;document.querySelector('#recipeCount').innerHTML=`Selecciona exactamente <b>${r.count}</b> ingredientes.`;document.querySelector('#recipeFeedback').textContent='';const box=document.querySelector('#ingredients');box.innerHTML=shuffle(r.options).map(x=>`<button class="ingredient">${x}</button>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(selected.has(b.textContent)){selected.delete(b.textContent);b.classList.remove('selected')}else{selected.add(b.textContent);b.classList.add('selected')}})};document.querySelector('#checkRecipe').onclick=()=>{const r=recipes[i],perfect=selected.size===r.correct.length&&r.correct.every(x=>selected.has(x));document.querySelector('#recipeFeedback').textContent=perfect?'✅ Receta perfecta':'❌ Revisa los ingredientes. Correctos: '+r.correct.join(', ');if(perfect)score++;setTimeout(()=>{i++;draw()},perfect?700:1800)};draw()}
function bindDilo(){const words=shuffle(diloWords).slice(0,5);let i=0;const draw=()=>{if(i>=5)return complete('dilo','Dilo sin decirlo superado','5 palabras jugadas');document.querySelector('#wordNum').textContent=i+1;document.querySelector('#word').textContent=words[i]};document.querySelector('#got').onclick=document.querySelector('#pass').onclick=()=>{i++;draw()};draw()}
function bindDrawing(){let i=0,int;const draw=()=>{if(i>=drawRounds.length)return complete('dibujo','Picasso en Pánico superado','3 obras maestras');document.querySelector('#roundNum').textContent=i+1;document.querySelector('#drawPrompt').textContent=drawRounds[i];document.querySelector('#drawTimer').textContent=30};document.querySelector('#startDraw').onclick=()=>{clearInterval(int);let n=30;document.querySelector('#drawTimer').textContent=n;int=setInterval(()=>{n--;document.querySelector('#drawTimer').textContent=n;if(n<=0){clearInterval(int);document.querySelector('#drawTimer').textContent='¡TIEMPO!'}},1000)};document.querySelector('#nextDraw').onclick=()=>{i++;draw()};draw()}
function bindWho(){const list=shuffle(people.filter(p=>p.img));let i=0,score=0;const draw=()=>{if(i>=list.length)return complete('quien','Experimento completado',`${score}/${list.length} aciertos`);const p=list[i];document.querySelector('.bar').style.width=`${(i/list.length)*100}%`;document.querySelector('#whoCount').textContent=`Experimento ${String(i+1).padStart(2,'0')} / ${list.length}`;document.querySelector('#whoMedia').innerHTML=`<img class="photo" src="${p.img}" alt="Persona transformada">`;const pool=people.filter(x=>x.group===p.group&&x.name!==p.name).map(x=>x.name);const opts=shuffle([p.name,...shuffle(pool).slice(0,3)]);const box=document.querySelector('#whoOptions');box.innerHTML=opts.map(x=>`<button class="option">${x}</button>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{box.querySelectorAll('button').forEach(x=>x.disabled=true);const ok=b.textContent===p.name;b.classList.add(ok?'correct':'wrong');if(ok)score++;setTimeout(()=>{i++;draw()},700)})};draw()}
function bindRandom(){let left=drawingWords.map((_,i)=>i+1);document.querySelector('#randomNumber').onclick=()=>{if(!left.length)left=drawingWords.map((_,i)=>i+1);const idx=Math.floor(Math.random()*left.length),n=left.splice(idx,1)[0];document.querySelector('#randomResult').textContent=`Número ${n}`}}
function confetti(){const c=document.createElement('div');c.className='confetti';document.body.appendChild(c);setTimeout(()=>c.remove(),1000)}
window.addEventListener('popstate',render);render();
