import { quizzes, songs, diloWords, drawRounds, people, differences } from '../data/game-data.js';
const $=s=>document.querySelector(s), app=$('#app');
let missions=[]; const stateKey='mbq-progress-v1';
const getState=()=>JSON.parse(localStorage.getItem(stateKey)||'{"done":{},"coins":30,"stars":0}');
const setState=s=>localStorage.setItem(stateKey,JSON.stringify(s));
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const esc=s=>String(s).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
fetch('data/missions.json').then(r=>r.json()).then(data=>{missions=data; render();});
function markDone(id,coins=100){const s=getState(); if(!s.done[id]){s.done[id]=true;s.stars=Object.keys(s.done).length;s.coins=(s.coins||0)+coins;setState(s);} confetti();}
function hud(){const s=getState(); return `<div class="hud"><span>❤️❤️❤️</span><span>🪙 <b>${s.coins||30}</b></span><span>⭐ <b>${Object.keys(s.done||{}).length}/${missions.length||11}</b></span><button class="sound" onclick="window.toggleSound()">🔊</button></div>`}
window.toggleSound=()=>alert('La música de ambiente está preparada para añadirla al final. Los clips de canciones sí funcionan dentro de Radio Retro.');
function render(){const id=new URLSearchParams(location.search).get('mission'); app.className='app'; app.innerHTML=hud()+(id?mission(id):home()); bind(id);}
function home(){const s=getState(); return `<section class="hero"><div class="title">Marina's<br>Birthday Quest</div><p class="subtitle">Nivel 30 desbloqueado 🍄</p><button class="btn" onclick="location.href='?mission=gamer'">▶ Empezar</button></section><section class="card"><h2>🗺️ Mapa de misiones</h2><div class="grid">${missions.map(m=>`<button class="mission ${s.done[m.id]?'done':''}" onclick="location.href='?mission=${m.id}'"><div class="ico">${m.icon}</div><h3>${m.title}</h3><p>${s.done[m.id]?'✅ completada':'🔒 disponible'}</p></button>`).join('')}</div></section><div class="footer"><button class="btn secondary" onclick="localStorage.removeItem('${stateKey}');location.reload()">Reiniciar progreso</button></div>`}
function mission(id){const m=missions.find(x=>x.id===id); if(!m)return `<section class="card"><h2>Misión no encontrada</h2><button class="btn" onclick="location.href='./'">Volver</button></section>`; if(quizzes[id]) return quizHtml(id,m); if(id==='musica') return musicHtml(m); if(id==='dilo') return cardsHtml(m); if(id==='perros') return dogsHtml(m); if(id==='letras') return letrasHtml(m); if(id==='dibujo') return dibujoHtml(m); if(id==='inutil') return inutilHtml(m); if(id==='diferencias') return diffHtml(m); if(id==='quien') return whoHtml(m); return `<section class="card"><h2>${m.icon} ${m.title}</h2><p>En construcción.</p></section>`}
function intro(m,text){return `<section class="hero"><div class="title">${m.icon} ${m.title}</div><p>${text||'Misión desbloqueada.'}</p><button class="btn secondary" onclick="location.href='./'">← Mapa</button></section>`}
function complete(id,title,score=''){return `<section class="hero"><div class="title">🏆 Mission Complete</div><h2>${title}</h2><p>${score}</p><p>⭐ +1 estrella &nbsp; 🪙 +100 monedas</p><button class="btn" onclick="location.href='./'">Volver al mapa</button></section>`}
function quizHtml(id,m){const q=quizzes[id]; return intro(m,q.intro)+`<section class="card" id="quiz" data-id="${id}" data-i="0" data-score="0"><div class="progress"><div class="bar"></div></div><div class="q"></div><div class="opts"></div></section>`}
function bindQuiz(id){const data=quizzes[id]; const box=$('#quiz'); if(!box)return; const draw=()=>{let i=+box.dataset.i, score=+box.dataset.score; if(i>=data.questions.length){const ok=score>=data.pass;if(ok)markDone(id); app.innerHTML=hud()+complete(id, ok?'¡Superado!':'Casi casi...',`${score}/${data.questions.length} aciertos`); return;} const item=data.questions[i]; $('.bar').style.width=((i)/data.questions.length*100)+'%'; $('.q').innerHTML=`Pregunta ${i+1}/${data.questions.length}<br>${esc(item.q).replaceAll('\n','<br>')}`; $('.opts').innerHTML=shuffle(item.options).map(o=>`<button class="option">${esc(o)}</button>`).join(''); document.querySelectorAll('.option').forEach(b=>b.onclick=()=>{const correct=b.textContent===item.a; b.classList.add(correct?'correct':'wrong'); if(correct)box.dataset.score=score+1; setTimeout(()=>{box.dataset.i=i+1; draw();},650);});}; draw();}
function musicHtml(m){return intro(m,'Escucha 5 segundos y adivina la canción.')+`<section class="card" id="music" data-i="0" data-score="0"><div class="progress"><div class="bar"></div></div><div class="record"></div><button class="btn" id="playSong">▶ Reproducir 5 segundos</button><div class="opts"></div><audio id="audio"></audio></section>`}
function bindMusic(){const box=$('#music'); if(!box)return; const audio=$('#audio'), rec=$('.record'); const draw=()=>{let i=+box.dataset.i, score=+box.dataset.score; if(i>=songs.length){markDone('musica'); app.innerHTML=hud()+complete('musica','Radio Retro superada',`${score}/${songs.length} canciones`);return;} $('.bar').style.width=(i/songs.length*100)+'%'; const song=songs[i]; audio.src=song.file; $('.opts').innerHTML=''; $('#playSong').disabled=false; $('#playSong').textContent=`▶ Pista ${i+1}/${songs.length}`; $('#playSong').onclick=()=>{audio.currentTime=0; audio.play(); rec.classList.add('playing'); $('#playSong').disabled=true; setTimeout(()=>{audio.pause(); rec.classList.remove('playing'); showOpts(song,i,score);},5000);};}; const showOpts=(song,i,score)=>{$('.opts').innerHTML=shuffle([song.title,...shuffle(songs.filter(s=>s.title!==song.title)).slice(0,3).map(s=>s.title)]).map(o=>`<button class="option">${esc(o)}</button>`).join(''); document.querySelectorAll('.option').forEach(b=>b.onclick=()=>{const ok=b.textContent===song.title;b.classList.add(ok?'correct':'wrong'); if(ok)box.dataset.score=score+1;setTimeout(()=>{box.dataset.i=i+1;draw();},700);});}; draw();}
function cardsHtml(m){return intro(m,'Haz que el resto adivine sin decir la palabra, derivados ni señalar.')+`<section class="card" id="cards" data-i="0"><h2>⏱️ 90 segundos</h2><div class="big-word"></div><button class="btn ok" id="got">✔️ Adivinada</button><button class="btn secondary" id="pass">⏭️ Pasar</button></section>`}
function bindCards(){const box=$('#cards'); if(!box)return; const words=diloWords; const draw=()=>{let i=+box.dataset.i; if(i>=words.length){markDone('dilo');app.innerHTML=hud()+complete('dilo','Dilo sin decirlo superado','5 cartas jugadas');return;} $('.big-word').textContent=words[i]; $('#got').onclick=$('#pass').onclick=()=>{box.dataset.i=i+1;draw();};};draw();}
function dogsHtml(m){return intro(m,'Tienes 30 segundos para decir 15 razas de perros.')+`<section class="card"><div class="timer" id="dogTimer">30</div><button class="btn" id="startDog">▶ Empezar</button><button class="btn ok" id="finishDog" style="display:none">Misión superada</button><p>Normas: no repetir razas y no vale “mestizo”.</p></section>`}
function bindDogs(){let t; $('#startDog')?.addEventListener('click',()=>{let n=30; $('#startDog').style.display='none'; $('#finishDog').style.display='inline-flex'; t=setInterval(()=>{$('#dogTimer').textContent=--n;if(n<=0)clearInterval(t)},1000);}); $('#finishDog')?.addEventListener('click',()=>{markDone('perros');app.innerHTML=hud()+complete('perros','Dog Master superado','15 razas nombradas');});}
function letrasHtml(m){return intro(m,'Dos personas se enfrentan en la Arena de las Letras.')+`<section class="card"><h2>⚔️ Cómo se juega</h2><p>A la de 3, cada jugador dice una letra. Hay que decir una palabra que empiece por la letra del jugador izquierdo y termine por la letra del jugador derecho.</p><p><b>Ejemplo:</b> S + A → SUELA.</p><p>El primero que diga una palabra válida gana. El ganador reta a otra persona hasta derrotar a todos.</p><button class="btn ok" id="doneLetras">Marcar como superado</button></section>`}
function dibujoHtml(m){return intro(m,'Dibuja sin levantar el lápiz. 30 segundos por ronda.')+`<section class="card" id="draw" data-i="0"><div class="big-word"></div><div class="timer" id="drawTimer">30</div><button class="btn" id="startDraw">▶ Iniciar ronda</button><button class="btn secondary" id="nextDraw">Siguiente</button></section>`}
function bindDibujo(){const box=$('#draw'); if(!box)return; const draw=()=>{let i=+box.dataset.i; if(i>=drawRounds.length){markDone('dibujo');app.innerHTML=hud()+complete('dibujo','Picasso en Pánico superado','3 rondas dibujadas');return;} $('.big-word').textContent=drawRounds[i]; $('#drawTimer').textContent=30;}; $('#startDraw').onclick=()=>{let n=30; const int=setInterval(()=>{$('#drawTimer').textContent=--n;if(n<=0)clearInterval(int)},1000)}; $('#nextDraw').onclick=()=>{box.dataset.i=+box.dataset.i+1;draw();};draw();}
function inutilHtml(m){return intro(m,'Un minuto exacto para mostrar tu talento inútil.')+`<section class="card"><p>Puede ser una voz rara, un chiste malo, doblar los dedos raro o cualquier cosa absurda. Cuanto más inútil, mejor.</p><div class="timer" id="inutilTimer">60</div><button class="btn" id="startInutil">▶ Empezar minuto</button><button class="btn ok" id="doneInutil">Gran Maestro de lo Inútil</button></section>`}
function bindInutil(){ $('#startInutil')?.addEventListener('click',()=>{let n=60; const int=setInterval(()=>{$('#inutilTimer').textContent=--n;if(n<=0)clearInterval(int)},1000)}); $('#doneInutil')?.addEventListener('click',()=>{markDone('inutil');app.innerHTML=hud()+complete('inutil','El Minuto Inútil superado','El grupo vota al Gran Maestro');});}
function diffHtml(m){return intro(m,'Toca en la imagen donde veas una diferencia. Esta versión deja el motor listo; iremos sustituyendo por las fotos finales individuales.')+`<section class="card" id="diff" data-photo="0" data-found="0"><h2></h2><p><b id="foundText">0/7</b> diferencias</p><div class="photoWrap"><img class="photo" id="diffImg"></div><button class="btn secondary" id="nextPhoto">Siguiente foto</button></section>`}
function bindDiff(){const box=$('#diff'); if(!box)return; const wrap=$('.photoWrap'), img=$('#diffImg'); let found=[]; const draw=()=>{let p=+box.dataset.photo; if(p>=differences.length){markDone('diferencias',300);app.innerHTML=hud()+complete('diferencias','Álbum completado','4 fotos completadas');return;} found=[]; const d=differences[p]; $('h2').textContent=`Foto ${p+1}/4`; img.src=d.img; $('#foundText').textContent='0/7'; document.querySelectorAll('.target').forEach(e=>e.remove());}; wrap.onclick=e=>{const p=+box.dataset.photo, d=differences[p]; const rect=img.getBoundingClientRect(); const x=(e.clientX-rect.left)/rect.width*100, y=(e.clientY-rect.top)/rect.height*100; d.points.forEach((pt,idx)=>{if(found.includes(idx))return; if(Math.hypot(pt[0]-x,pt[1]-y)<8){found.push(idx); const c=document.createElement('div'); c.className='target'; c.style.left=pt[0]+'%'; c.style.top=pt[1]+'%'; c.style.width=c.style.height='42px'; wrap.appendChild(c); $('#foundText').textContent=`${found.length}/7`; if(found.length===7)setTimeout(()=>alert('Foto completada ✅'),100);}})}; $('#nextPhoto').onclick=()=>{box.dataset.photo=+box.dataset.photo+1;draw();}; draw();}
function whoHtml(m){return intro(m,'Adivina quién es cada persona transformada.')+`<section class="card" id="who" data-i="0" data-score="0"><div class="progress"><div class="bar"></div></div><img class="photo answerImg" id="whoImg"><div class="opts"></div></section>`}
function bindWho(){const box=$('#who'); if(!box)return; const list=shuffle(people); const draw=()=>{let i=+box.dataset.i, score=+box.dataset.score;if(i>=list.length){markDone('quien');app.innerHTML=hud()+complete('quien','¿Quién es quién? superado',`${score}/${list.length} aciertos`);return;} const p=list[i]; $('.bar').style.width=(i/list.length*100)+'%'; $('#whoImg').src=p.img; const pool=people.filter(x=>x.group===p.group&&x.name!==p.name).map(x=>x.name); const opts=shuffle([p.name,...shuffle(pool).slice(0,3)]); $('.opts').innerHTML=opts.map(o=>`<button class="option">${esc(o)}</button>`).join(''); document.querySelectorAll('.option').forEach(b=>b.onclick=()=>{const ok=b.textContent===p.name;b.classList.add(ok?'correct':'wrong'); if(ok)box.dataset.score=score+1; setTimeout(()=>{box.dataset.i=i+1;draw();},750);});};draw();}
function bind(id){ if(quizzes[id])bindQuiz(id); if(id==='musica')bindMusic(); if(id==='dilo')bindCards(); if(id==='perros')bindDogs(); if(id==='letras')$('#doneLetras')?.addEventListener('click',()=>{markDone('letras');app.innerHTML=hud()+complete('letras','Duelo de Letras superado','Arena conquistada');}); if(id==='dibujo')bindDibujo(); if(id==='inutil')bindInutil(); if(id==='diferencias')bindDiff(); if(id==='quien')bindWho(); }
window.addEventListener('popstate',render); function confetti(){const d=document.createElement('div');d.className='confetti';document.body.appendChild(d);setTimeout(()=>d.remove(),900)}
