const questions=[{q:"🍄 ¿Qué personaje ayuda a Mario durante toda la aventura en Super Mario Odyssey?",a:["Tiara","Cappy","Lubba","Kamek"],correct:1},{q:"👻 En Luigi's Mansion 3, ¿dónde transcurre la aventura principal?",a:["En un hotel encantado","En un castillo","En una nave","En una isla"],correct:0},{q:"🌙 ¿Qué necesita la Odyssey para viajar entre reinos?",a:["Estrellas","Power Moons","Monedas rojas","Champiñones dorados"],correct:1},{q:"🌾 ¿Quién te regala la primera caña de pescar en Stardew Valley?",a:["Lewis","Robin","Willy","Gus"],correct:2},{q:"⛏️ En Stardew Valley, ¿qué zona desbloquea el combate y la minería?",a:["La playa","Las minas","El saloon","El autobús"],correct:1},{q:"🚨 En Among Us, ¿qué pasa cuando alguien reporta un cadáver?",a:["Se inicia una reunión","Gana el impostor","Se reinicia el mapa","Se cierran todas las puertas"],correct:0},{q:"🛠️ ¿Qué enemigo clásico de Mario lanza martillos?",a:["Lakitu","Goomba","Hammer Bro","Koopa Troopa"],correct:2},{q:"🏙️ ¿Cuál de estos reinos SÍ aparece en Super Mario Odyssey?",a:["Reino Lava","Reino Metro","Reino Trueno","Reino Hielo Eterno"],correct:1},{q:"🧪 ¿Cómo se llama el profesor que ayuda a Luigi en Luigi's Mansion?",a:["Profesor Oak","Profesor Fesor / E. Gadd","Profesor K. Rool","Profesor Toad"],correct:1},{q:"🛰️ En Among Us, si todos los tripulantes completan sus tareas antes de ser eliminados, ¿qué ocurre?",a:["Gana el impostor","Ganan los tripulantes","Hay ronda extra","Se cambia de mapa"],correct:1}];
const startScreen=document.getElementById('startScreen'),quizScreen=document.getElementById('quizScreen'),endScreen=document.getElementById('endScreen'),startBtn=document.getElementById('startBtn'),restartBtn=document.getElementById('restartBtn'),soundBtn=document.getElementById('soundBtn'),qText=document.getElementById('questionText'),qCount=document.getElementById('questionCount'),answers=document.getElementById('answers'),feedback=document.getElementById('feedback'),progressBar=document.getElementById('progressBar'),coins=document.getElementById('coins'),finalTitle=document.getElementById('finalTitle'),finalScore=document.getElementById('finalScore'),finalText=document.getElementById('finalText'),stars=document.getElementById('stars');
let current=0,score=0,audioCtx,musicTimer,musicOn=false;
function show(screen){[startScreen,quizScreen,endScreen].forEach(s=>s.classList.remove('active'));screen.classList.add('active')}
function playTone(freq,duration=.08,type='square',volume=.05){if(!audioCtx||!musicOn)return;const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type=type;osc.frequency.value=freq;gain.gain.value=volume;osc.connect(gain);gain.connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+duration)}
function startMusic(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();musicOn=true;soundBtn.textContent='🔊 música';const melody=[523,659,784,659,523,392,440,494];let i=0;clearInterval(musicTimer);musicTimer=setInterval(()=>{playTone(melody[i%melody.length],.09,'square',.025);i++},210)}
function stopMusic(){musicOn=false;soundBtn.textContent='🔇 música';clearInterval(musicTimer)}
function renderQuestion(){feedback.textContent='';const item=questions[current];qCount.textContent=`PREGUNTA ${current+1} / ${questions.length}`;qText.textContent=item.q;progressBar.style.width=`${current/questions.length*100}%`;answers.innerHTML='';item.a.forEach((text,idx)=>{const btn=document.createElement('button');btn.className='answer-btn';btn.textContent=text;btn.onclick=()=>chooseAnswer(btn,idx);answers.appendChild(btn)})}
function chooseAnswer(btn,idx){[...answers.children].forEach(b=>b.disabled=true);const item=questions[current];if(idx===item.correct){score++;coins.textContent=score;btn.classList.add('correct');feedback.textContent='✅ ¡Correcto! +1 moneda';playTone(880,.12,'square',.08);setTimeout(()=>playTone(1175,.12,'square',.08),100)}else{btn.classList.add('wrong');answers.children[item.correct].classList.add('correct');feedback.textContent='💀 Casi... respuesta desbloqueada';playTone(180,.22,'sawtooth',.07)}setTimeout(()=>{current++;current<questions.length?renderQuestion():endGame()},1200)}
function endGame(){progressBar.style.width='100%';show(endScreen);finalScore.textContent=`${score} / ${questions.length} respuestas correctas`;stars.textContent='⭐'.repeat(Math.max(1,Math.round(score/2)));if(score>=7){finalTitle.textContent='MISIÓN COMPLETADA';finalText.textContent='Marina ha demostrado que es una auténtica Gamer Nivel 30. Reclama tu estrella al NPC.';playTone(660,.12);setTimeout(()=>playTone(880,.12),120);setTimeout(()=>playTone(1320,.25),250)}else{finalTitle.textContent='GAME OVER';finalText.textContent='Has estado cerca... pero el Reino Champiñón exige revancha.';playTone(220,.25,'sawtooth',.07);setTimeout(()=>playTone(160,.35,'sawtooth',.07),220)}}
startBtn.onclick=()=>{startMusic();current=0;score=0;coins.textContent='0';show(quizScreen);renderQuestion()};restartBtn.onclick=()=>{current=0;score=0;coins.textContent='0';show(quizScreen);renderQuestion()};soundBtn.onclick=()=>musicOn?stopMusic():startMusic();
